### ISSUE TITLE
[PE-D] Confusing sentence structure for untake example

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W17-2/tp#131]
![image.png](https://raw.githubusercontent.com/kheekheekhee/ped/main/files/c5358d4c-fbc9-49fd-8fc2-ab8f04fdcd2b.png)

Shouldn't it be "untake 1 is equivalent to removing the 1st module in the database from the schedule"?

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: kheekheekhee/ped#4

**Comment by El0hime** [comment]
Nothing wrong with sentence structure, 1 presents the 1st module in the database and not the 1st module in the schedule
