### ISSUE TITLE
[PE-D] Definition of "year" sounds very weird

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W17-2/tp#139]
![image.png](https://raw.githubusercontent.com/kheekheekhee/ped/main/files/e520497b-84eb-4f04-ab4a-d10c4e29a709.png)

maybe it can be "represents academic year that the specified module is being taken in" or something else along those lines

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: kheekheekhee/ped#6

**Comment by El0hime** [comment]
Issue resolved in #170
