### ISSUE TITLE
[PE-D] Sudden shift towards non-you language in command terminology

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W17-2/tp#142]
![image.png](https://raw.githubusercontent.com/kheekheekhee/ped/main/files/13c49658-bfad-454d-ae8d-719c3201f2a9.png)

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: kheekheekhee/ped#7

**Comment by El0hime** [comment]
Issue resolved in #170
