### ISSUE TITLE
[PE-D] [SUGGESTION] Unnecessary Command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W17-2/tp#150]
### Summary 
Info is unnecessary as you can see your mc goal and your year on the bottom bar, or on the side bar. Having an additional command called `info` just makes it confusing

### Expected Value 
1. Should there be `info` command, the bottom bar

![image.png](https://raw.githubusercontent.com/simonjulianl/ped/main/files/bc2ef930-f70e-4861-9388-341ce45b1b03.png)

Should not display the info anymore, otherwise its redundant. Similarly with the side bar 

![image.png](https://raw.githubusercontent.com/simonjulianl/ped/main/files/4bb68d5b-9c64-444e-a2c5-9f5ea77e59fe.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: simonjulianl/ped#11

**Comment by El0hime** [comment]
Issue resolved in #170
