### ISSUE TITLE
[PE-D] MC bar not proportional

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W17-2/tp#151]
![image.png](https://raw.githubusercontent.com/TLChicken/ped/main/files/bc0950ca-b31f-43b6-8a87-ab7219a7da4f.png)

When 1 quarter of the MCs are taken, the bar is not filled up proportionally.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: TLChicken/ped#13

**Comment by jodichoo** [comment]
Proportions of the progress bar is difficult to fix due to limitations with the javafx progressbar component, the ratio used for the progress bar fill has been checked and confirmed to be correct.
