### ISSUE TITLE
[PE-D] m prefix takes in letters in User Guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W17-2/tp#156]
![image.png](https://raw.githubusercontent.com/TLChicken/ped/main/files/a46fc299-d18b-4d01-8816-d13c04d2fb7d.png)

... the different commands only use the m prefix for MCs which only takes in integers

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: TLChicken/ped#15

**Comment by El0hime** [comment]
Issue resolved in #170
