### ISSUE TITLE
[PE-D] Missing List and Exit Command in Command summary

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W17-2/tp#158]
![image.png](https://raw.githubusercontent.com/elroygohjy/ped/main/files/e40c5b67-ee8c-4d3b-9d27-861776ce1793.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: elroygohjy/ped#12

**Comment by El0hime** [comment]
Issue resolved in #170
