### ISSUE TITLE
[PE-D] Not well defined definition:  Current Semester

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W17-2/tp#159]
![image.png](https://raw.githubusercontent.com/elroygohjy/ped/main/files/f2831865-910c-482f-b8e8-3d8d77a6260e.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: elroygohjy/ped#13

**Comment by El0hime** [comment]
Issue resolved in #170
