### ISSUE TITLE
[PE-D] UG wrong description

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W17-2/tp#162]
![image.png](https://raw.githubusercontent.com/elroygohjy/ped/main/files/70bdc6c4-446a-4130-b2ae-f25910435902.png)
The bar is grey..

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: elroygohjy/ped#16

**Comment by El0hime** [comment]
Issue resolved in #170
