### ISSUE TITLE
[PE-D] UG bugs for other issues

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S1-CS2103T-W17-2/tp#164]
- Just a suggestion to have one table of content for UG, not two.
- For "Find" feature, I think it is clearer to emphasise that a spacing is needed after the prefix.

-------------
Labels: `type.DocumentationBug` `severity.Low`
original: jhlee1997/ped#3

**Comment by El0hime** [comment]
Issue resolved in #170
